require('./functions/health')
require('./functions/sites')
require('./functions/clients')
require('./functions/deviceConfig')
require('./functions/gudePower')
require('./functions/clientSettings')
require('./functions/userPreferences')
require('./functions/domotz')
